// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFLXC2Qbe0wAtJ47s1MU6GwOGygnYUdTg',
    appId: '1:1088106376530:web:67d8784767dae15b691e8b',
    messagingSenderId: '1088106376530',
    projectId: 'moneymaster-5772c',
    authDomain: 'moneymaster-5772c.firebaseapp.com',
    storageBucket: 'moneymaster-5772c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0PvnXLRaopL2oMsmc-jTyYvn4pszDn1A',
    appId: '1:1088106376530:android:f6025be1602924ba691e8b',
    messagingSenderId: '1088106376530',
    projectId: 'moneymaster-5772c',
    storageBucket: 'moneymaster-5772c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFLXC2Qbe0wAtJ47s1MU6GwOGygnYUdTg',
    appId: '1:1088106376530:web:2f3f570ece2ef537691e8b',
    messagingSenderId: '1088106376530',
    projectId: 'moneymaster-5772c',
    authDomain: 'moneymaster-5772c.firebaseapp.com',
    storageBucket: 'moneymaster-5772c.firebasestorage.app',
  );
}
